replicaCount: 2

image:
  repository: 824987503353.dkr.ecr.us-west-2.amazonaws.com/harness
  tag: <+stage.variables.image_tag>
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

app:
  name: aedifex-app

DEPLOY_MESSAGE: <+serviceVariables.DEPLOY_MESSAGE>
