replicaCount: 2

image:
  repository: 824987503353.dkr.ecr.us-west-2.amazonaws.com/harness
  tag: 71
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

app:
  name: aedifex-app

DEPLOY_MESSAGE: "hello from values.yaml"